version: "3.9"

services:
  api:
    build: ./api
    container_name: indux-api
    restart: always
    env_file: .env
    depends_on:
      - mongo
      - minio
    networks:
      - shared_caddy_net
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - MONGO_URI=${MONGO_URI}
      - S3_ENDPOINT=${S3_ENDPOINT}
      - PUBLIC_S3_ENDPOINT=${PUBLIC_S3_ENDPOINT}
      - S3_ACCESS_KEY=${S3_ACCESS_KEY}
      - S3_SECRET_KEY=${S3_SECRET_KEY}
      - S3_BUCKET=${S3_BUCKET}
      - S3_REGION=${S3_REGION}
      - S3_USE_SSL=${S3_USE_SSL}
      - JWT_ACCESS_SECRET=${JWT_ACCESS_SECRET}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
      - ACCESS_TOKEN_TTL=${ACCESS_TOKEN_TTL}
      - REFRESH_TOKEN_TTL=${REFRESH_TOKEN_TTL}
      - FRONTEND_URL=${FRONTEND_URL}
      - SEED=${SEED}

  frontend:
    build: ./frontend
    container_name: indux-frontend
    restart: always
    networks:
      - shared_caddy_net
    ports:
      - "5173:80"

  mongo:
    image: mongo:7
    container_name: indux-mongo
    restart: always
    volumes:
      # 🔒 volumen externo fijo (con datos existentes)
      - mongo_data:/data/db
    networks:
      - shared_caddy_net
    ports:
      - "27017:27017"

  minio:
    image: minio/minio:latest
    container_name: indux-minio
    restart: always
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${S3_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${S3_SECRET_KEY}
    volumes:
      # 🔒 volumen externo fijo (persistente)
      - minio_data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - shared_caddy_net

# 🔐 VOLUMENES FIJOS Y EXTERNOS (NO SE RECREAN EN REDEPLOY)
volumes:
  mongo_data:
    external: true
    name: indux-frontend-2p8dqs_mongo_data
  minio_data:
    external: true
    name: indux_minio_data

# 🌐 RED EXISTENTE (CADDY / OTROS SERVICIOS)
networks:
  shared_caddy_net:
    external: true
