version: "3.9"

networks:
  shared_caddy_net:
    external: true

volumes:
  mongo_data:
    name: indux_mongo_data
  minio_data:
    name: indux_minio_data

services:
  mongo:
    image: mongo:7
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - shared_caddy_net

  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=${S3_ACCESS_KEY}
      - MINIO_ROOT_PASSWORD=${S3_SECRET_KEY}
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    networks:
      - shared_caddy_net

  api:
    build: ./api
    restart: unless-stopped
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${PORT}
      - MONGO_URI=${MONGO_URI}
      - JWT_ACCESS_SECRET=${JWT_ACCESS_SECRET}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
      - ACCESS_TOKEN_TTL=${ACCESS_TOKEN_TTL}
      - REFRESH_TOKEN_TTL=${REFRESH_TOKEN_TTL}
      # --- S3 / MinIO ---
      - S3_ENDPOINT=${S3_ENDPOINT}               # ej: http://minio:9000
      - S3_REGION=${S3_REGION}                   # ej: us-east-1
      - S3_BUCKET=${S3_BUCKET}                   # ej: indux
      - S3_ACCESS_KEY=${S3_ACCESS_KEY}
      - S3_SECRET_KEY=${S3_SECRET_KEY}
      - S3_USE_SSL=${S3_USE_SSL}                 # ej: false
      - PUBLIC_S3_ENDPOINT=${PUBLIC_S3_ENDPOINT} # 👈 NECESARIO para firmar HTTPS público
      # --- Mail ---
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}
      - MAIL_FROM=${MAIL_FROM}
      # --- CORS / URLs ---
      - FRONTEND_URL=${FRONTEND_URL}
      - VITE_API_URL=${VITE_API_URL}
      # --- Seed ---
      - SEED=${SEED}
    expose:
      - "8080"
    depends_on:
      - mongo
      - minio
    networks:
      - shared_caddy_net

  frontend:
    build:
      context: ./frontend
      args:
        - VITE_API_URL=${VITE_API_URL} # en prod recomendado: /api
    restart: unless-stopped
    environment:
      - VITE_API_URL=${VITE_API_URL}
    expose:
      - "80"
    depends_on:
      - api
    networks:
      - shared_caddy_net
