version: "3.9"

# 🔗 RED COMPARTIDA ENTRE CADDY Y DEMÁS SERVICIOS
networks:
  shared_caddy_net:
    external: true

# 📦 VOLÚMENES PERSISTENTES
volumes:
  mongo_data:
    external: true
    name: indux_mongo_data
  minio_data:
    external: true
    name: indux_minio_data

services:
  # 🧱 MongoDB (seguro y persistente)
  mongo:
    image: mongo:7
    container_name: indux-mongo
    restart: unless-stopped
    # ❌ NUNCA publicar el puerto al exterior
    # ports:
    #   - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER:-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS:-supersecurepassword}
    volumes:
      - mongo_data:/data/db
    networks:
      - shared_caddy_net
    command: ["mongod"]

  # 📁 MinIO (S3-compatible)
  minio:
    image: minio/minio:latest
    container_name: indux-minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${S3_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${S3_SECRET_KEY}
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    networks:
      - shared_caddy_net

  # ⚙️ Backend (Express + TypeScript)
  api:
    build: ./api
    container_name: indux-api
    restart: unless-stopped
    environment:
      NODE_ENV: ${NODE_ENV}
      PORT: ${PORT}
      MONGO_URI: mongodb://${MONGO_USER:-admin}:${MONGO_PASS:-supersecurepassword}@mongo:27017/indux?authSource=admin
      JWT_ACCESS_SECRET: ${JWT_ACCESS_SECRET}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET}
      ACCESS_TOKEN_TTL: ${ACCESS_TOKEN_TTL}
      REFRESH_TOKEN_TTL: ${REFRESH_TOKEN_TTL}
      # --- MinIO / S3 ---
      S3_ENDPOINT: ${S3_ENDPOINT}
      S3_REGION: ${S3_REGION}
      S3_BUCKET: ${S3_BUCKET}
      S3_ACCESS_KEY: ${S3_ACCESS_KEY}
      S3_SECRET_KEY: ${S3_SECRET_KEY}
      S3_USE_SSL: ${S3_USE_SSL}
      PUBLIC_S3_ENDPOINT: ${PUBLIC_S3_ENDPOINT}
      # --- Mail ---
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASS: ${SMTP_PASS}
      MAIL_FROM: ${MAIL_FROM}
      # --- URLs y CORS ---
      FRONTEND_URL: ${FRONTEND_URL}
      # --- Seed inicial ---
      SEED: ${SEED}
    expose:
      - "8080"
    depends_on:
      - mongo
      - minio
    networks:
      - shared_caddy_net

  # 🌐 Frontend (React + Vite + Nginx)
  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: ${VITE_API_URL}
    container_name: indux-frontend
    restart: unless-stopped
    environment:
      VITE_API_URL: ${VITE_API_URL}
    expose:
      - "80"
    depends_on:
      - api
    networks:
      - shared_caddy_net
