import { Router } from 'express';
import bcrypt from 'bcryptjs';
import { requireAuth, requireRole } from '../middleware/auth.js';
import { User } from '../models/User.js';
import { UserCreateSchema, UserUpdateSchema } from '../utils/validators.js';

const router = Router();

// List users (admin)
router.get('/', requireAuth, requireRole('admin'), async (_req, res) => {
  // Exclude the password hash from responses
  const users = await User.find().select('-password').sort({ createdAt: -1 });
  res.json(users);
});

// Create user (admin)
router.post('/', requireAuth, requireRole('admin'), async (req, res) => {
  // Generate a temporary password if missing
  const body = { ...req.body } as any;
  let autoGenerated = false;

  if (!body.password || String(body.password).trim() === '') {
    body.password = generateRandomPassword(8);
    autoGenerated = true;
  }

  // Validamos con Zod (password puede ser la generada automáticamente)
  const parsed = UserCreateSchema.safeParse(body);
  if (!parsed.success) return res.status(400).json({ error: parsed.error.flatten() });

  try {
    const { email, name, role, password, position, phone, companyName, avatarUrl } = parsed.data;
    const exists = await User.findOne({ email });
    if (exists) return res.status(409).json({ error: 'Email already exists' });

    // Store the bcrypt hash in the 'password' field (used by login)
    const passwordHash = await bcrypt.hash(password, 10);
    const user = await User.create({ email, name, role, password: passwordHash, position, phone, companyName, avatarUrl });

    const payload: any = {
      id: user._id,
      email: user.email,
      name: user.name,
      role: user.role,
      disabled: user.disabled,
      position: user.position,
      phone: user.phone,
      companyName: user.companyName,
      avatarUrl: user.avatarUrl,
    };
    if (autoGenerated) {
      // Informative message for client-side UX/logs
      payload.info = 'Password was required and generated automatically.';
    }
    res.status(201).json(payload);
  } catch (e: any) {
    // Readable error response, avoid server crash
    return res.status(500).json({ error: e?.message || 'Failed to create user' });
  }
});

// Update user (admin)
router.put('/:id', requireAuth, requireRole('admin'), async (req, res) => {
  const parsed = UserUpdateSchema.safeParse(req.body);
  if (!parsed.success) return res.status(400).json({ error: parsed.error.flatten() });

  try {
    const patch: any = { ...parsed.data };
    if (patch.password) {
      // Persist the hash in 'password' (used by login)
      patch.password = await bcrypt.hash(patch.password, 10);
    }
    const updated = await User.findByIdAndUpdate(req.params.id, patch, { new: true }).select('-password');
    if (!updated) return res.status(404).json({ error: 'User not found' });
    res.json(updated);
  } catch (e: any) {
    return res.status(500).json({ error: e?.message || 'Failed to update user' });
  }
});

// Generador simple de contraseñas alfanuméricas
function generateRandomPassword(length: number) {
  const chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789';
  let out = '';
  for (let i = 0; i < length; i++) {
    out += chars.charAt(Math.floor(Math.random() * chars.length));
  }
  return out;
}

// Delete user (admin) – soft delete by disabling
router.delete('/:id', requireAuth, requireRole('admin'), async (req, res) => {
  try {
    const deleted = await User.findByIdAndDelete(req.params.id);
    if (!deleted) return res.status(404).json({ error: 'User not found' });
    res.json({ ok: true });
  } catch (e: any) {
    return res.status(500).json({ error: e?.message || 'Failed to delete user' });
  }
});

export default router;
