import { Router } from 'express';
import bcrypt from 'bcryptjs';
import { requireAuth, requireRole } from '../middleware/auth.js';
import { User } from '../models/User.js';
import { UserCreateSchema, UserUpdateSchema } from '../utils/validators.js';

const router = Router();

// List users (admin)
router.get('/', requireAuth, requireRole('admin'), async (_req, res) => {
  // Excluimos el hash de contraseña siguiendo el esquema actual (campo: password)
  const users = await User.find().select('-password').sort({ createdAt: -1 });
  res.json(users);
});

// Create user (admin)
router.post('/', requireAuth, requireRole('admin'), async (req, res) => {
  // Genera una contraseña temporal si no viene en el body
  const body = { ...req.body } as any;
  let autoGenerated = false;

  if (!body.password || String(body.password).trim() === '') {
    body.password = generateRandomPassword(8);
    autoGenerated = true;
  }

  // Validamos con Zod (password puede ser la generada automáticamente)
  const parsed = UserCreateSchema.safeParse(body);
  if (!parsed.success) return res.status(400).json({ error: parsed.error.flatten() });

  try {
    const { email, name, role, password } = parsed.data;
    const exists = await User.findOne({ email });
    if (exists) return res.status(409).json({ error: 'Email already exists' });

    // Guardamos el hash en el campo actual del modelo (password)
    const passwordHash = await bcrypt.hash(password, 10);
    const user = await User.create({ email, name, role, password: passwordHash });

    const payload: any = { id: user._id, email: user.email, name: user.name, role: user.role, disabled: user.disabled };
    if (autoGenerated) {
      // Mensaje informativo para trazabilidad del frontend/logs
      payload.info = 'El campo password era requerido y se generó automáticamente.';
    }
    res.status(201).json(payload);
  } catch (e: any) {
    // Respuesta legible en caso de error inesperado
    return res.status(500).json({ error: e?.message || 'Error al crear usuario' });
  }
});

// Update user (admin)
router.put('/:id', requireAuth, requireRole('admin'), async (req, res) => {
  const parsed = UserUpdateSchema.safeParse(req.body);
  if (!parsed.success) return res.status(400).json({ error: parsed.error.flatten() });

  try {
    const patch: any = { ...parsed.data };
    if (patch.password) {
      // Persistimos el hash en el campo password (es el que usa el login)
      patch.password = await bcrypt.hash(patch.password, 10);
    }
    const updated = await User.findByIdAndUpdate(req.params.id, patch, { new: true }).select('-password');
    if (!updated) return res.status(404).json({ error: 'User not found' });
    res.json(updated);
  } catch (e: any) {
    return res.status(500).json({ error: e?.message || 'Error al actualizar usuario' });
  }
});

// Generador simple de contraseñas alfanuméricas
function generateRandomPassword(length: number) {
  const chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789';
  let out = '';
  for (let i = 0; i < length; i++) {
    out += chars.charAt(Math.floor(Math.random() * chars.length));
  }
  return out;
}

// Delete user (admin) – soft delete by disabling
router.delete('/:id', requireAuth, requireRole('admin'), async (req, res) => {
  await User.findByIdAndUpdate(req.params.id, { disabled: true });
  res.json({ ok: true });
});

export default router;
